---
- name: Install st2
  hosts: all
  environment: "{{ st2_proxy_env | default({}) }}"
  roles:
    - StackStorm.mongodb
    - StackStorm.rabbitmq
    - StackStorm.postgresql
    - StackStorm.st2repo
    - name: install and configure st2
      role: StackStorm.st2
      vars:
        st2_version: latest
        st2_auth_enable: yes
        st2_save_credentials: yes
        st2_system_user: stanley
        st2_system_user_in_sudoers: yes
    # - StackStorm.st2mistral
    - StackStorm.nginx
    - StackStorm.st2web
    - StackStorm.nodejs
    - StackStorm.st2chatops
    - StackStorm.st2smoketests
    - role: StackStorm.ewc
      when: ewc_license is defined and ewc_license is not none and ewc_license | length > 0
    - role: StackStorm.ewc_smoketests
      when: ewc_license is defined and ewc_license is not none and ewc_license | length > 0
    # https://github.com/networklore/ansible-role-nagios
    - name: install and configure nagios
      role: ansible-role-nagios
      vars:
        with_httpd_conf: /etc/apache2/conf-available
